os: linux
language: perl
perl:
    - "5.22.1"
    - "5.16.1"
    - "5.18.3"

matrix:
  fast_finish: true
  include:
    - perl: 5.22.1
      env: COVERAGE=1   # enables coverage+coveralls reporting

before_install:
     - eval $(curl https://travis-perl.github.io/init) --auto
